"""added cars table

Revision ID: 5b190d121761
Revises: 
Create Date: 2023-10-13 04:47:59.427894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5b190d121761"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cars",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("url", sa.VARCHAR(length=768), nullable=False),
        sa.Column("title", sa.VARCHAR(length=255), nullable=False),
        sa.Column("price_usd", sa.INTEGER(), nullable=False),
        sa.Column("odometer", sa.BIGINT(), nullable=True),
        sa.Column("username", sa.VARCHAR(length=255), nullable=True),
        sa.Column("image_url", sa.TEXT(), nullable=True),
        sa.Column("images_count", sa.SMALLINT(), nullable=False),
        sa.Column("car_number", sa.VARCHAR(length=255), nullable=True),
        sa.Column("car_vin", sa.VARCHAR(length=255), nullable=True),
        sa.Column("phone_number", sa.BIGINT(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_cars_url"), "cars", ["url"], unique=True, schema="public"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_public_cars_url"), table_name="cars", schema="public")
    op.drop_table("cars", schema="public")
    # ### end Alembic commands ###
