"""alter phone_number column

Revision ID: 6d1fd49e8fb0
Revises: 5b190d121761
Create Date: 2023-10-13 15:44:19.536121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6d1fd49e8fb0"
down_revision: Union[str, None] = "5b190d121761"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("cars", "phone_number", existing_type=sa.BIGINT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cars",
        "phone_number",
        existing_type=sa.BIGINT(),
        nullable=False,
        server_default=sa.text("0"),
    )
    # ### end Alembic commands ###
